const menu = [
    {
      id: 1,
      title: 'Erizos',
      category: 'Entradas Frías',
      price: 15000,
      img: '../images/platos/entradas_frias/erizos.png',
      desc: `Erizos bañados en su salsa, convinada con perejil y especias `,
    },
    {
      id: 2,
      title: 'Locos',
      category: 'Entradas Frías',
      price: 16000,
      img: '../images/platos/entradas_frias/locos.png',
      desc: `Locos Frescos con diferentes salsas `,
    },
    {
      id: 3,
      title: 'Mix de Mariscos',
      category: 'Entradas Frías',
      price: 13500,
      img: '../images/platos/entradas_frias/mix_de_mariscos.png',
      desc: `5 mariscos marinados con salsa de hierbas, mayonesa de la casa y pebre  `,
    },
    {
      id: 4,
      title: 'Chupe de Jaiba',
      category: 'Plato de Fondo',
      price: 14000,
      img: '../images/platos/platos_fondo/chupe_de_jaiba.png',
      desc: `Chupe de jaiba con queso parmesano `,
    },
    {
      id: 5,
      title: 'Atún con Papas',
      category: 'Plato de Fondo',
      price: 15000,
      img: '../images/platos/platos_fondo/atun.png',
      desc: `Atún cocinado en su punto con papas fritas `,
    },
    {
      id: 6,
      title: 'Camarones al Pil Pil',
      category: 'Plato de Fondo',
      price: 13000,
      img: '../images/platos/platos_fondo/camarones_al_pilpil.png',
      desc: `Camarones al pil pil con crema y cacho de cabra`,
    },
    {
      id: 7,
      title: 'Machas a la Parmesana',
      category: 'Plato de Fondo',
      price: 15000,
      img: '../images/platos/platos_fondo/machas_a_la_parmesana.png',
      desc: `Machas con queso parmesano cocidas en vino blanco`,
    },
    {
      id: 8,
      title: 'Mix de Mariscos al Pil Pil',
      category: 'Plato de Fondo',
      price: 14000,
      img: '../images/platos/platos_fondo/paila_al_pilpil.png',
      desc: `Mix de sabores marinos al pil pil`,
    },
    {
      id: 9,
      title: 'Paila Marina',
      category: 'Platos de Fondo',
      price: 13000,
      img: '../images/platos/platos_fondo/paila_marina.png',
      desc: `Paila Marina con frutos del mar y pescado`,
    },

    {
        id: 10,
        title: 'Tiramisu',
        category: 'Postre',
        price: 4500,
        img: '../images/platos/postres/tiramisu.png',
        desc: `Postre Tiramisu acompañado con helado`,
      },

      {
        id: 11,
        title: 'Panqueque de Platano',
        category: 'Postre',
        price: 4500,
        img: '../images/platos/postres/panqueque_de_platano.png',
        desc: `Panqueque de platanos dorados`,
      },

      {
        id: 12,
        title: 'Panna Cotta',
        category: 'Postre',
        price: 4500,
        img: '../images/platos/postres/panna_cotta.png',
        desc: `Panna cotta de chocolate`,
      },
  ];
  export default menu;